name: siemens_hackathon_safety_marker
description: An app used for safety assurance of miners and workers in mines and factories.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  authentication:
    path: packages/authentication
  bloc: ^7.0.0
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  firebase_core: ^1.5.0
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
