name: authentication
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cache:
    path: ../cache
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  fake_cloud_firestore: ^1.1.2
  firebase_auth_mocks: ^0.8.0
